baseURL = "https://navihub.net/"
languageCode = "zh-CN"
title = "navihub.net 一个对导航进行导航的网站"
theme = "navi"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
copyright = ""
[params]
  author = "vxiaozhi"
  description = "navihub.net 一个对导航进行导航的网站"
[params.search]
  enable = true
[params.darkmode]
  enable = false